// flow-typed signature: 7c8a9390c72ed1518a4aff91cd9ef356
// flow-typed version: <<STUB>>/imagemin-jpegtran_v^6.0.0/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'imagemin-jpegtran'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'imagemin-jpegtran' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'imagemin-jpegtran/index' {
  declare module.exports: $Exports<'imagemin-jpegtran'>;
}
declare module 'imagemin-jpegtran/index.js' {
  declare module.exports: $Exports<'imagemin-jpegtran'>;
}
