// flow-typed signature: c6aab7055c67aa742498f022f818d63e
// flow-typed version: <<STUB>>/imagemin-svgo_v^7.0.0/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'imagemin-svgo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'imagemin-svgo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'imagemin-svgo/index' {
  declare module.exports: $Exports<'imagemin-svgo'>;
}
declare module 'imagemin-svgo/index.js' {
  declare module.exports: $Exports<'imagemin-svgo'>;
}
