// flow-typed signature: 88fc5a9715d968e2eb724242cb07204a
// flow-typed version: <<STUB>>/imagemin-pngquant_v^7.0.0/flow_v0.90.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'imagemin-pngquant'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'imagemin-pngquant' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'imagemin-pngquant/index' {
  declare module.exports: $Exports<'imagemin-pngquant'>;
}
declare module 'imagemin-pngquant/index.js' {
  declare module.exports: $Exports<'imagemin-pngquant'>;
}
