// flow-typed signature: 49c4297548c552e6adff32a0a320b333
// flow-typed version: <<STUB>>/imagemin-pngquant_v^6.0.0/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'imagemin-pngquant'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'imagemin-pngquant' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'imagemin-pngquant/index' {
  declare module.exports: $Exports<'imagemin-pngquant'>;
}
declare module 'imagemin-pngquant/index.js' {
  declare module.exports: $Exports<'imagemin-pngquant'>;
}
