// flow-typed signature: ddc5f6faac75d98792d32985c964f4a6
// flow-typed version: <<STUB>>/imagemin-gifsicle_v^6.0.1/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'imagemin-gifsicle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'imagemin-gifsicle' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'imagemin-gifsicle/index' {
  declare module.exports: $Exports<'imagemin-gifsicle'>;
}
declare module 'imagemin-gifsicle/index.js' {
  declare module.exports: $Exports<'imagemin-gifsicle'>;
}
